import type { CategoryConfig, PropertyListing } from "@/lib/types";

export const categoryConfigs: CategoryConfig[] = [
  { label: "Properties for rent", group: "properties", purpose: "rent", visible: true },
  { label: "Properties for sale", group: "properties", purpose: "sale", visible: true },
  { label: "Cars for sale", group: "cars", purpose: "sale", category: "car", visible: false },
  { label: "Cars for rent", group: "cars", purpose: "rent", category: "car", visible: false },
];

export const propertyCategories = [
  "house",
  "apartment",
  "villa",
  "land",
  "office",
  "retail",
] as const;

export const sampleListings: PropertyListing[] = [
  {
    id: "ip-001",
    title: "Furnished villa with rooftop views in Kibagabaga",
    slug: "furnished-villa-rooftop-kibagabaga",
    group: "properties",
    purpose: "rent",
    category: "villa",
    status: "published",
    location: "Kibagabaga",
    district: "Gasabo",
    price: 2500,
    currency: "USD",
    bedrooms: 5,
    bathrooms: 5,
    areaSqm: 420,
    images: [
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=75",
    ],
    summary: "A calm, secure home with wide terraces, furnished interiors, and quick access to KG roads.",
    features: ["Rooftop terrace", "Furnished", "Garden", "Staff quarters"],
    agentName: "Ipopo Rwanda",
    phone: "+250788000000",
    whatsapp: "+250788000000",
    featured: true,
    createdAt: "2026-05-20T08:00:00.000Z",
  },
  {
    id: "ip-002",
    title: "Modern two bedroom apartment in Kacyiru",
    slug: "modern-two-bedroom-apartment-kacyiru",
    group: "properties",
    purpose: "rent",
    category: "apartment",
    status: "published",
    location: "Kacyiru",
    district: "Gasabo",
    price: 900,
    currency: "USD",
    bedrooms: 2,
    bathrooms: 2,
    areaSqm: 118,
    images: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1200&q=75",
    ],
    summary: "Bright apartment near offices, restaurants, embassies, and central Kigali amenities.",
    features: ["Balcony", "Backup water", "Parking", "Fiber ready"],
    agentName: "Ipopo Rwanda",
    phone: "+250788000000",
    whatsapp: "+250788000000",
    featured: true,
    createdAt: "2026-05-28T08:00:00.000Z",
  },
  {
    id: "ip-003",
    title: "Family house for sale near Rebero ridge",
    slug: "family-house-sale-rebero-ridge",
    group: "properties",
    purpose: "sale",
    category: "house",
    status: "published",
    location: "Rebero",
    district: "Kicukiro",
    price: 260000000,
    currency: "RWF",
    bedrooms: 4,
    bathrooms: 4,
    areaSqm: 360,
    images: [
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=75",
    ],
    summary: "Move-in ready house with green outlooks, strong construction, and excellent resale potential.",
    features: ["Title ready", "Tarmac access", "Quiet neighborhood", "Open kitchen"],
    agentName: "Ipopo Rwanda",
    phone: "+250788000000",
    whatsapp: "+250788000000",
    featured: true,
    createdAt: "2026-06-02T08:00:00.000Z",
  },
  {
    id: "ip-004",
    title: "Prime residential plot in Nyarutarama",
    slug: "prime-residential-plot-nyarutarama",
    group: "properties",
    purpose: "sale",
    category: "land",
    status: "published",
    location: "Nyarutarama",
    district: "Gasabo",
    price: 185000000,
    currency: "RWF",
    areaSqm: 720,
    images: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1400&q=80",
    ],
    summary: "A rare residential parcel in one of Kigali's most requested addresses.",
    features: ["Residential zoning", "Utilities nearby", "Good frontage", "Investment grade"],
    agentName: "Ipopo Rwanda",
    phone: "+250788000000",
    whatsapp: "+250788000000",
    createdAt: "2026-06-06T08:00:00.000Z",
  },
];
