import type { CategoryConfig, PropertyListing } from "@/lib/types";

export const categoryConfigs: CategoryConfig[] = [
  { label: "Properties for rent", group: "properties", purpose: "rent", visible: true },
  { label: "Properties for sale", group: "properties", purpose: "sale", visible: true },
  { label: "Cars for sale", group: "cars", purpose: "sale", category: "car", visible: true },
  { label: "Cars for rent", group: "cars", purpose: "rent", category: "car", visible: true },
];

export const propertyCategories = [
  "house",
  "apartment",
  "villa",
  "land",
  "office",
  "retail",
] as const;

export const sampleListings: PropertyListing[] = [
  {
    id: "ip-001",
    title: "Furnished villa with rooftop views in Kibagabaga",
    slug: "furnished-villa-rooftop-kibagabaga",
    group: "properties",
    purpose: "rent",
    category: "villa",
    status: "published",
    location: "Kibagabaga",
    district: "Gasabo",
    price: 2500,
    currency: "USD",
    bedrooms: 5,
    bathrooms: 5,
    areaSqm: 420,
    images: [
      "/images/properties/prop-04.jpg",
      "/images/properties/prop-07.jpg",
    ],
    summary: "A calm, secure home with wide terraces, furnished interiors, and quick access to KG roads.",
    features: ["Rooftop terrace", "Furnished", "Garden", "Staff quarters"],
    agentName: "Ipopo Rwanda",
    phone: "+250788000000",
    whatsapp: "+250788000000",
    featured: true,
    createdAt: "2026-05-20T08:00:00.000Z",
  },
  {
    id: "ip-002",
    title: "Modern two bedroom apartment in Kacyiru",
    slug: "modern-two-bedroom-apartment-kacyiru",
    group: "properties",
    purpose: "rent",
    category: "apartment",
    status: "published",
    location: "Kacyiru",
    district: "Gasabo",
    price: 900,
    currency: "USD",
    bedrooms: 2,
    bathrooms: 2,
    areaSqm: 118,
    images: [
      "/images/properties/prop-01.jpg",
      "/images/properties/prop-02.jpg",
    ],
    summary: "Bright apartment near offices, restaurants, embassies, and central Kigali amenities.",
    features: ["Balcony", "Backup water", "Parking", "Fiber ready"],
    agentName: "Ipopo Rwanda",
    phone: "+250788000000",
    whatsapp: "+250788000000",
    featured: true,
    createdAt: "2026-05-28T08:00:00.000Z",
  },
  {
    id: "ip-003",
    title: "Family house for sale near Rebero ridge",
    slug: "family-house-sale-rebero-ridge",
    group: "properties",
    purpose: "sale",
    category: "house",
    status: "published",
    location: "Rebero",
    district: "Kicukiro",
    price: 260000000,
    currency: "RWF",
    bedrooms: 4,
    bathrooms: 4,
    areaSqm: 360,
    images: [
      "/images/properties/prop-15.jpg",
      "/images/properties/prop-14.jpg",
    ],
    summary: "Move-in ready house with green outlooks, strong construction, and excellent resale potential.",
    features: ["Title ready", "Tarmac access", "Quiet neighborhood", "Open kitchen"],
    agentName: "Ipopo Rwanda",
    phone: "+250788000000",
    whatsapp: "+250788000000",
    featured: true,
    createdAt: "2026-06-02T08:00:00.000Z",
  },
  {
    id: "ip-004",
    title: "Prime residential plot in Nyarutarama",
    slug: "prime-residential-plot-nyarutarama",
    group: "properties",
    purpose: "sale",
    category: "land",
    status: "published",
    location: "Nyarutarama",
    district: "Gasabo",
    price: 185000000,
    currency: "RWF",
    areaSqm: 720,
    images: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1400&q=80",
    ],
    summary: "A rare residential parcel in one of Kigali's most requested addresses.",
    features: ["Residential zoning", "Utilities nearby", "Good frontage", "Investment grade"],
    agentName: "Ipopo Rwanda",
    phone: "+250788000000",
    whatsapp: "+250788000000",
    createdAt: "2026-06-06T08:00:00.000Z",
  },
  {
    id: "ip-005",
    title: "Executive apartment with city skyline in Gacuriro",
    slug: "executive-apartment-city-skyline-gacuriro",
    group: "properties",
    purpose: "rent",
    category: "apartment",
    status: "published",
    location: "Gacuriro",
    district: "Gasabo",
    price: 1450,
    currency: "USD",
    bedrooms: 3,
    bathrooms: 3,
    areaSqm: 168,
    images: [
      "/images/properties/prop-03.jpg",
      "/images/properties/prop-11.jpg",
    ],
    summary: "A polished apartment with a generous balcony, concierge feel, and fast access to the city center.",
    features: ["City view", "Elevator", "Security", "Modern kitchen"],
    agentName: "Ipopo Rwanda",
    phone: "+250788000000",
    whatsapp: "+250788000000",
    featured: true,
    createdAt: "2026-06-07T08:00:00.000Z",
  },
  {
    id: "ip-006",
    title: "Boutique office suite near Kigali Heights",
    slug: "boutique-office-suite-kigali-heights",
    group: "properties",
    purpose: "rent",
    category: "office",
    status: "published",
    location: "Kimihurura",
    district: "Gasabo",
    price: 3200,
    currency: "USD",
    areaSqm: 240,
    images: [
      "/images/properties/prop-08.jpg",
      "/images/properties/prop-17.jpg",
    ],
    summary: "High-visibility office space for a serious team that wants address, access, and premium presentation.",
    features: ["Reception", "Boardroom", "Generator", "Fiber internet"],
    agentName: "Ipopo Rwanda",
    phone: "+250788000000",
    whatsapp: "+250788000000",
    featured: true,
    createdAt: "2026-06-08T08:00:00.000Z",
  },
  {
    id: "ip-007",
    title: "Luxury hilltop residence in Nyarutarama",
    slug: "luxury-hilltop-residence-nyarutarama",
    group: "properties",
    purpose: "sale",
    category: "villa",
    status: "published",
    location: "Nyarutarama",
    district: "Gasabo",
    price: 650000,
    currency: "USD",
    bedrooms: 6,
    bathrooms: 6,
    areaSqm: 580,
    images: [
      "/images/properties/prop-12.jpg",
      "/images/properties/prop-04.jpg",
    ],
    summary: "A statement home with layered terraces, premium finishes, and long-term investment appeal.",
    features: ["Pool-ready", "Panoramic views", "Cinema room", "Private gate"],
    agentName: "Ipopo Rwanda",
    phone: "+250788000000",
    whatsapp: "+250788000000",
    featured: true,
    createdAt: "2026-06-09T08:00:00.000Z",
  },
  {
    id: "ip-008",
    title: "Retail showroom on a busy Remera road",
    slug: "retail-showroom-busy-remera-road",
    group: "properties",
    purpose: "rent",
    category: "retail",
    status: "published",
    location: "Remera",
    district: "Gasabo",
    price: 1800,
    currency: "USD",
    areaSqm: 155,
    images: [
      "/images/properties/prop-13.jpg",
      "/images/properties/prop-05.jpg",
    ],
    summary: "Street-facing commercial space for showroom, clinic, retail, or brand-led customer experience.",
    features: ["Road frontage", "Glass facade", "Parking", "High footfall"],
    agentName: "Ipopo Rwanda",
    phone: "+250788000000",
    whatsapp: "+250788000000",
    createdAt: "2026-06-10T08:00:00.000Z",
  },
  {
    id: "ip-009",
    title: "Serviced studio apartments in Kiyovu",
    slug: "serviced-studio-apartments-kiyovu",
    group: "properties",
    purpose: "rent",
    category: "apartment",
    status: "published",
    location: "Kiyovu",
    district: "Nyarugenge",
    price: 650,
    currency: "USD",
    bedrooms: 1,
    bathrooms: 1,
    areaSqm: 64,
    images: [
      "/images/properties/prop-11.jpg",
      "/images/properties/prop-17.jpg",
    ],
    summary: "Compact, furnished, and well-managed studios for executives, consultants, and long-stay guests.",
    features: ["Serviced", "Furnished", "Laundry", "Central location"],
    agentName: "Ipopo Rwanda",
    phone: "+250788000000",
    whatsapp: "+250788000000",
    createdAt: "2026-06-11T08:00:00.000Z",
  },
  {
    id: "ip-010",
    title: "Development land near Bugesera corridor",
    slug: "development-land-bugesera-corridor",
    group: "properties",
    purpose: "sale",
    category: "land",
    status: "published",
    location: "Kanombe",
    district: "Kicukiro",
    price: 98000000,
    currency: "RWF",
    areaSqm: 1200,
    images: [
      "https://images.unsplash.com/photo-1516156008625-3a9d6067fab5?auto=format&fit=crop&w=1400&q=80",
    ],
    summary: "Strategic parcel for investors tracking airport corridor growth and Kigali expansion.",
    features: ["Large plot", "Road access", "Growth corridor", "Clean paperwork"],
    agentName: "Ipopo Rwanda",
    phone: "+250788000000",
    whatsapp: "+250788000000",
    createdAt: "2026-06-12T08:00:00.000Z",
  },
  {
    id: "ip-011",
    title: "Contemporary family home in Kibagabaga",
    slug: "contemporary-family-home-kibagabaga",
    group: "properties",
    purpose: "sale",
    category: "house",
    status: "published",
    location: "Kibagabaga",
    district: "Gasabo",
    price: 310000000,
    currency: "RWF",
    bedrooms: 5,
    bathrooms: 5,
    areaSqm: 410,
    images: [
      "/images/properties/prop-03.jpg",
      "/images/properties/prop-02.jpg",
    ],
    summary: "A modern family residence with clean finishes, generous rooms, and easy neighborhood access.",
    features: ["Family layout", "Secure gate", "Garden", "Modern finishes"],
    agentName: "Ipopo Rwanda",
    phone: "+250788000000",
    whatsapp: "+250788000000",
    createdAt: "2026-06-12T14:00:00.000Z",
  },
  {
    id: "ip-012",
    title: "Penthouse apartment near Kigali Convention Centre",
    slug: "penthouse-apartment-kigali-convention-centre",
    group: "properties",
    purpose: "rent",
    category: "apartment",
    status: "published",
    location: "Kimihurura",
    district: "Gasabo",
    price: 2100,
    currency: "USD",
    bedrooms: 3,
    bathrooms: 3,
    areaSqm: 190,
    images: [
      "/images/properties/prop-14.jpg",
      "/images/properties/prop-15.jpg",
    ],
    summary: "An executive penthouse with wide city views and a polished address for work and lifestyle.",
    features: ["Penthouse", "City view", "Elevator", "Backup power"],
    agentName: "Ipopo Rwanda",
    phone: "+250788000000",
    whatsapp: "+250788000000",
    featured: true,
    createdAt: "2026-06-12T15:00:00.000Z",
  },
  {
    id: "ip-013",
    title: "Quiet townhouse compound in Kacyiru",
    slug: "quiet-townhouse-compound-kacyiru",
    group: "properties",
    purpose: "rent",
    category: "house",
    status: "published",
    location: "Kacyiru",
    district: "Gasabo",
    price: 1250,
    currency: "USD",
    bedrooms: 3,
    bathrooms: 3,
    areaSqm: 210,
    images: [
      "/images/properties/prop-02.jpg",
      "/images/properties/prop-01.jpg",
    ],
    summary: "A practical, peaceful townhouse close to offices, schools, and central Kigali connections.",
    features: ["Compound", "Parking", "Family friendly", "Close to offices"],
    agentName: "Ipopo Rwanda",
    phone: "+250788000000",
    whatsapp: "+250788000000",
    createdAt: "2026-06-12T16:00:00.000Z",
  },
  {
    id: "ip-014",
    title: "Corner commercial plot in Remera",
    slug: "corner-commercial-plot-remera",
    group: "properties",
    purpose: "sale",
    category: "land",
    status: "published",
    location: "Remera",
    district: "Gasabo",
    price: 240000000,
    currency: "RWF",
    areaSqm: 860,
    images: [
      "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1400&q=80",
    ],
    summary: "A visible corner plot for mixed-use development, showroom, or long-term commercial hold.",
    features: ["Corner plot", "Commercial potential", "Visible frontage", "Utilities nearby"],
    agentName: "Ipopo Rwanda",
    phone: "+250788000000",
    whatsapp: "+250788000000",
    createdAt: "2026-06-12T17:00:00.000Z",
  },
  {
    id: "car-001",
    title: "Range Rover Sport HSE for executive hire",
    slug: "range-rover-sport-hse-executive-hire",
    group: "cars",
    purpose: "rent",
    category: "car",
    status: "published",
    location: "Kigali",
    district: "Kigali",
    price: 180,
    currency: "USD",
    images: [
      "/images/hero/kigali-car-hero.png",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=75",
    ],
    summary: "Premium SUV for airport pickup, executive movement, events, and luxury Kigali travel.",
    features: ["Driver option", "Airport pickup", "Luxury SUV", "Daily rental"],
    agentName: "Ipopo Rwanda",
    phone: "+250788000000",
    whatsapp: "+250788000000",
    featured: true,
    createdAt: "2026-06-12T10:00:00.000Z",
  },
  {
    id: "car-002",
    title: "Toyota Land Cruiser Prado ready for sale",
    slug: "toyota-land-cruiser-prado-sale-kigali",
    group: "cars",
    purpose: "sale",
    category: "car",
    status: "published",
    location: "Kigali",
    district: "Kigali",
    price: 38500,
    currency: "USD",
    images: [
      "https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1200&q=75",
    ],
    summary: "Clean, comfortable, and trusted SUV for family use, business errands, and Rwanda roads.",
    features: ["4x4", "Automatic", "Clean interior", "Inspection ready"],
    agentName: "Ipopo Rwanda",
    phone: "+250788000000",
    whatsapp: "+250788000000",
    featured: true,
    createdAt: "2026-06-12T11:00:00.000Z",
  },
  {
    id: "car-003",
    title: "Mercedes-Benz GLE for VIP transfer",
    slug: "mercedes-benz-gle-vip-transfer",
    group: "cars",
    purpose: "rent",
    category: "car",
    status: "published",
    location: "Kacyiru",
    district: "Gasabo",
    price: 220,
    currency: "USD",
    images: [
      "https://images.unsplash.com/photo-1617814076668-5e58051fd8e6?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=75",
    ],
    summary: "A refined VIP option for conferences, embassy movement, and premium client transfers.",
    features: ["VIP service", "Chauffeur", "Leather interior", "Event ready"],
    agentName: "Ipopo Rwanda",
    phone: "+250788000000",
    whatsapp: "+250788000000",
    createdAt: "2026-06-12T12:00:00.000Z",
  },
  {
    id: "car-004",
    title: "Toyota RAV4 hybrid for sale in Kigali",
    slug: "toyota-rav4-hybrid-sale-kigali",
    group: "cars",
    purpose: "sale",
    category: "car",
    status: "published",
    location: "Remera",
    district: "Gasabo",
    price: 28500,
    currency: "USD",
    images: [
      "https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=75",
    ],
    summary: "Efficient, practical, and sharp-looking crossover for Kigali daily driving.",
    features: ["Hybrid", "Automatic", "Low consumption", "Family friendly"],
    agentName: "Ipopo Rwanda",
    phone: "+250788000000",
    whatsapp: "+250788000000",
    createdAt: "2026-06-12T13:00:00.000Z",
  },
];
